[package]
name = "vespera"
version = "0.1.0"
edition = "2024"

[dependencies]
vespera-core = { path = "../vespera-core" }
vespera-macro = { path = "../vespera_macro", package = "vespera_macro" }
axum = "0.8"
